spring.application.name=labreserve

spring.datasource.url=jdbc:h2:mem:labreserve;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jackson.datatype.datetime.write-dates-as-timestamps=false

app.jwt.secret=YVAOdS5XichHrBeK6Xwzqpn9lKYb8sjNSYMMur0aBoem+No/s/YS8XO8i+6+Sg9R
app.jwt.expiration-seconds=3600
